services:
  mysql:
    image: mysql:8.0
    container_name: shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: shop-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql-data: