spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://shop-mysql:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update        # prod는 validate — 실수로 스키마 변경 방지(배포 처음 실행 시 db 에러를 위해 update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  data:
    redis:
      host: shop-redis
      port: 6379
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    root: warn
    com.study.shop: info

jwt:
  secret: ${JWT_SECRET}         # 환경변수로 주입