spring:
  datasource:
    url: ${DB_URL}            # 예: jdbc:postgresql://host:5432/shop
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate      # 운영은 스키마 검증만 (권장)
  # 마이그레이션 도구 사용 시
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: false

# 운영에선 Swagger/H2 콘솔 비활성
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# 운영 로깅은 보수적으로
logging:
  level:
    root: info
    com.study.cruisin: info
    org.hibernate.SQL: warn

# 서버 공통 하드닝 예(선택)
server:
  compression:
    enabled: true
  forward-headers-strategy: framework