spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  h2:
    console:
      enabled: false
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    com.study.shop: debug
#    org.springframework.web: debug
#    org.springframework.security: debug
    org.springframework.cache: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: SldUU2lnbmluZ0tleUZvclNlY3VyZUF1dGhlbnRpY2F0aW9uSW5TcHJpbmdCb290QXBwbGljYXRpb25XaXRoSFMyNTZBbGdvcml0aG0=

file:
  upload-dir: uploads/posts