spring:
  application:
    name: shop
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  profiles:
    active:
      dev

logging:
  level:
    root: warn
    com.study.shop: debug
    org.springframework: warn
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"

jwt:
  # secret: local.yml/environment variable로 관리
  access-expiration-ms: 1800000
  refresh-expiration-ms: 1209600000

file:
  upload-dir: uploads/posts