events {
    worker_connections 1024;
}

http {
    upstream spring_app {
        server shop-app:8080;
    }

    server {
        listen 80;
        server_name _;          # EC2 IP 또는 도메인으로 나중에 교체

        location / {
            proxy_pass http://spring_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr; // 조회수 로직 때문에 nginx ip로 전부 보이는것을 방지
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}